"""empty message

Revision ID: 83197e70ca56
Revises: f7d863ff32d2
Create Date: 2022-05-30 12:18:03.561540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83197e70ca56'
down_revision = 'f7d863ff32d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
