"""empty message

Revision ID: f7d863ff32d2
Revises: 68677e4b25c7
Create Date: 2022-05-28 11:51:05.893449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d863ff32d2'
down_revision = '68677e4b25c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(length=100), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    op.drop_column('Venue', 'talent_description')
    op.drop_column('Venue', 'websit_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('websit_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('talent_description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
